networks:
  default:
    enable_ipv6: true
services:
  warp_proxy:
    restart: always
    container_name: warp_proxy
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3129:3129'
    environment:
      # IPv6 broker support
      # use to obtain dedecated IPv6 addres for you proxy
      enable_ipv6_tunnel: false
      # tunnel broker settings
      # obtain free at:
      #  - https://ipv6.he.net/
      #  - http://tb.netassist.ua/
      #  - https://ipv6.ip4market.ru/
      #  - https://6in4.ru/
      # and others:
      #  - https://tunnelbroker.services/
      #  - https://handwiki.org/wiki/List_of_IPv6_tunnel_brokers
      #  - https://www.arin.net/vault/participate/meetings/reports/ARIN_XXIII/pdf/sunday/ipv6_tunnel_brokers.pdf
      tunnel_server_ip4_addr: '<broker ip4>'
      tunnel_ttl: 255
      tunnel_mtu: 1480
      tunnel_client_ip6_addr: '<your ip6>'
      tunnel_server_ip6_addr: '<broker ip6>'
      tunnel_route_add_cmd_ip6: '<ip6 route add command if needed (see your broker docs)>'
      # these DNSs are supporting resolving v6 queries over v4
      # so recommended for tunnel
      proxy_dns: '8.8.8.8, 1.1.1.1'
      # proxy auth creds
      # leavy empty to disable
      # how to test: `curl v6.ipinfo.io/ip  --proxy '127.0.0.1:3129' -U warp_proxy:changeme -v`
      proxy_username: 'warp_proxy'
      proxy_password: 'changeme'
    # basically your 3proxy service config is stored here
    volumes:
      - ./conf:/usr/local/3proxy/conf
