networks:
  default:
    enable_ipv6: true
services:
  warp_proxy:
    restart: always
    container_name: warp_proxy
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3129:3129'
    environment:
      # enable if you need dedicated IPv6 address in the proxy
      enable_ipv6_tunnel: false
      # IPv6 broker tunnel option
      # obtain for free at
      # http://tb.netassist.ua/
      # https://ipv6.he.net/
      # https://ipv6.ip4market.ru/
      # https://6in4.ru/
      # and etc
      tunnel_server_ip4_addr: '95.213.189.133'
      tunnel_ttl: 255
      tunnel_mtu: 1480
      tunnel_client_ip6_addr: '2a06:1301:4725::48a/127'
      tunnel_server_ip6_addr: '2a06:1301:4725::48b/127'
      tunnel_route_add_cmd_ip6: 'ip -6 route add 2000::/3 dev ipv6'
      # which proxy will use proxy
      # these proxies are supporting v6 domain resolving over v4 protocol
      # so recommended with v6 tunnel
      proxy_dns: '8.8.8.8, 1.1.1.1'
      # auth creds for you proxy
      # test: `curl v6.ipinfo.io/ip --proxy '127.0.0.1:3129' -U warp_proxy:changeme -v`
      proxy_username: 'warp_proxy'
      proxy_password: 'changeme2'
    volumes:
      - ./conf:/usr/local/3proxy/conf
